---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: study-service-sa
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: study-service
  template:
    metadata:
      labels:
        app: study-service
    spec:
      serviceAccountName: study-service-sa
      containers:
        - name: study-service
          image: study-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_CONFIG_NAME
              value: bootstrap-k8s
            - name: SPRING_CONFIG_LOCATION
              value: classpath:/bootstrap.yml
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SERVER_PORT
              value: "8084"
            - name: SPRING_CLOUD_VAULT_URI
              value: http://vault.vault.svc.cluster.local:8200
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888

          # Health checks (Spring Boot Actuator)
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: study-service
spec:
  selector:
    app: study-service
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
